// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workshop.Infrastructure.Persistence;

#nullable disable

namespace Workshop.Infrastructure.Migrations
{
    [DbContext(typeof(WorkshopDbContext))]
    partial class WorkshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workshop")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workshop.Domain.Aggregates.BudgetModel.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_on");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_order_id");

                    b.Property<int>("TotalPriceCents")
                        .HasColumnType("int")
                        .HasColumnName("total_price_cents");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("budgets", "workshop");
                });

            modelBuilder.Entity("Workshop.Domain.Aggregates.ServiceOrderModel.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("OSCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("os_code");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OSCode"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("service_orders", "workshop");
                });

            modelBuilder.Entity("Workshop.Domain.Aggregates.BudgetModel.Budget", b =>
                {
                    b.OwnsMany("Workshop.Domain.Aggregates.BudgetModel.BudgetConsumable", "Consumables", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<Guid>("ConsumableId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("consumable_id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<int>("PriceCents")
                                .HasColumnType("int")
                                .HasColumnName("price_cents");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("budget_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("budget_id");

                            b1.ToTable("budget_consumables", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("budget_id");
                        });

                    b.OwnsMany("Workshop.Domain.Aggregates.BudgetModel.BudgetJob", "Jobs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<DateTime?>("ExecutedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("executed_on");

                            b1.Property<bool>("IsExecuted")
                                .HasColumnType("bit")
                                .HasColumnName("is_executed");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("job_id");

                            b1.Property<int>("PriceCents")
                                .HasColumnType("int")
                                .HasColumnName("price_cents");

                            b1.Property<Guid>("budget_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("budget_id");

                            b1.ToTable("budget_jobs", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("budget_id");
                        });

                    b.OwnsMany("Workshop.Domain.Aggregates.BudgetModel.BudgetPart", "Parts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("part_id");

                            b1.Property<int>("PriceCents")
                                .HasColumnType("int")
                                .HasColumnName("price_cents");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("budget_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("budget_id");

                            b1.ToTable("budget_parts", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("budget_id");
                        });

                    b.Navigation("Consumables");

                    b.Navigation("Jobs");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Workshop.Domain.Aggregates.ServiceOrderModel.ServiceOrder", b =>
                {
                    b.OwnsOne("Shared.Domain.Security.Actor", "CreatedBy", b1 =>
                        {
                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("created_by_type");

                            b1.HasKey("ServiceOrderId");

                            b1.ToTable("service_orders", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.OwnsMany("Workshop.Domain.Aggregates.ServiceOrderModel.ServiceOrderHistory", "Histories", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("message");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("status");

                            b1.Property<Guid>("service_order_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("service_order_id");

                            b1.ToTable("service_order_histories", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("service_order_id");

                            b1.OwnsOne("Shared.Domain.Security.Actor", "ChangedBy", b2 =>
                                {
                                    b2.Property<Guid>("ServiceOrderHistoryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("changed_by_id");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("changed_by_type");

                                    b2.HasKey("ServiceOrderHistoryId");

                                    b2.ToTable("service_order_histories", "workshop");

                                    b2.WithOwner()
                                        .HasForeignKey("ServiceOrderHistoryId");
                                });

                            b1.Navigation("ChangedBy")
                                .IsRequired();
                        });

                    b.OwnsMany("Workshop.Domain.Aggregates.ServiceOrderModel.ServiceOrderJob", "RequestedJobs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("job_id");

                            b1.Property<Guid>("service_order_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("service_order_id");

                            b1.ToTable("service_order_jobs", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("service_order_id");
                        });

                    b.OwnsMany("Workshop.Domain.Aggregates.ServiceOrderModel.ServiceOrderPart", "RequestedParts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("part_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("service_order_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("service_order_id");

                            b1.ToTable("service_order_parts", "workshop");

                            b1.WithOwner()
                                .HasForeignKey("service_order_id");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("Histories");

                    b.Navigation("RequestedJobs");

                    b.Navigation("RequestedParts");
                });
#pragma warning restore 612, 618
        }
    }
}
